version: "3.8"

services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: base
    volumes:
      - base-api-postgres-data:/var/lib/postgresql/data
      - ./init-db-scripts:/docker-entrypoint-initdb.d
    #    networks:
    #      - backend
    ports:
      - "5432:5432"

#networks:
#  backend:
#  frontend:

volumes:
  base-api-postgres-data: