version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-d10qnim3jp1c73997j70-a.singapore-postgres.render.com/base_f6hx
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=31Oha1Sg9zEeGJzCm0LrC4EDW2fCcE43
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge