version: "3.8"

services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: base
    volumes:
      - base-api-postgres-data:/var/lib/postgresql/data
      - ./init-db-scripts:/docker-entrypoint-initdb.d
    networks:
      - backend
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-d10qnim3jp1c73997j70-a.singapore-postgres.render.com
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=31Oha1Sg9zEeGJzCm0LrC4EDW2fCcE43
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgresSQLDialect
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  base-api-postgres-data: