spring:
  datasource:
    url: jdbc:postgresql://ec2-54-255-206-191.ap-southeast-1.compute.amazonaws.com:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    #open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
# ci/cd
server:
  error:
    whitelabel:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    #      springframework:
    #        security: TRACE
    hibernate:
      #        SQL: DEBUG
      orm:
        jdbc:
          bind: TRACE
      stat: DEBUG
      SQL_SLOW: INFO
      cache: DEBUG
jwt:
  signing:
    key: R+gzzzwVCSGby26qay8Ws/r9/2oWNd2ymD/OnKU+IVc=
