spring:
  mvc:
    problemdetails:
      enabled: true
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://root:31Oha1Sg9zEeGJzCm0LrC4EDW2fCcE43@dpg-d10qnim3jp1c73997j70-a/base_f6hx
    username: root
    password: 31Oha1Sg9zEeGJzCm0LrC4EDW2fCcE43
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect
        format_sql: true
  jackson:
    default-property-inclusion: non_null
  data:
    rest:
      base-path: /api

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  influx:
    metrics:
      export:
        api-version:

springdoc:
  api-docs:
    path: /docs/api-docs
    version: openapi_3_1
  swagger-ui:
    path: /docs/swagger-ui

jwt:
  signing:
    key: R+gzzzwVCSGby26qay8Ws/r9/2oWNd2ymD/OnKU+IVc=