spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
# spring:
#   datasource:
#     url: jdbc:postgresql://54.169.153.253:5432/postgres
#     username: postgres
#     password: password
#     driver-class-name: org.postgresql.Driver
jwt:
  signing:
    key: R+gzzzwVCSGby26qay8Ws/r9/2oWNd2ymD/OnKU+IVc=
