spring:
  mvc:
    problemdetails:
      enabled: true
  profiles:
    active: dev
  jpa:
    #open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        "[format_sql]": true

  jackson:
    # Skip serializing null fields
    default-property-inclusion: NON_NULL

  data:
    rest:
      base-path: /api

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

# FIXME: Limit Actuator endpoint exposure
management:
  endpoints:
    web:
      exposure:
        include: "*"
  influx:
    metrics:
      export:
        api-version:

#infinispan:
#  embedded:
#    cluster-name: buffalo-api
springdoc:
  api-docs:
    path: /docs/api-docs
    version: openapi_3_1
  swagger-ui:
    path: /docs/swagger-ui

jwt:
  signing:
    key: R+gzzzwVCSGby26qay8Ws/r9/2oWNd2ymD/OnKU+IVc=
